name: flutter_camp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter 
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2  
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.1 
  cupertino_icons: ^1.0.8

flutter_launcher_icons: 
  android: true
  image_path: "assets/icon/icon_camp.png"
  min_sdk_android: 24
  adptive_icon_background : "#ffffff"
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0




flutter:

 
  uses-material-design: true

  
